title: Lori's blog
description: >
  I am a engineer who likes to play with technologies and work on personal projects. This is a web archive that contains records of my journey, and the right place for you if you are like me!

baseurl: /blog
remote_theme: jekyll/minima
author:
  name: Lori
  email: haoanli@andrew.cmu.edu

header_pages:
  - about.md

minima:
  social_links:
    - { platform: github,         user_url: "https://github.com/lorilandly" }
    - { platform: google_scholar, user_url: "https://scholar.google.com/citations?user=ygZZJPgAAAAJ" }
    - { platform: instagram,      user_url: "https://www.instagram.com/the_loriland" }
    - { platform: linkedin,       user_url: "https://www.linkedin.com/in/lorilandly" }

google_analytics: G-FZXW6MDNQJ
